___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np
import pandas as pd

#### 2. Create an array from my_list=[5,10,15,20,25]

In [3]:
my_list = np.arange(5,26,5)
my_list

array([ 5, 10, 15, 20, 25])

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [8]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [10]:
np.ones((4,4),dtype=int) * 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [12]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [11]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [13]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [14]:
np.linspace(0,24,num=25,dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [18]:
np.random.rand(5)

array([0.06597575, 0.67523487, 0.76055481, 0.34829031, 0.98692911])

array([0.76358107, 0.87803301, 0.80945923, 0.58642508, 0.32335644])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [22]:
np.random.randn(5,5)

array([[-1.1603856 , -0.45240412,  1.0196468 ,  0.94753118, -0.4931052 ],
       [-1.19481804, -1.20748472, -1.27114131,  0.33251715,  0.24242311],
       [-0.3192665 , -0.1919411 , -0.28981992, -0.83178169,  0.16424424],
       [-0.26860706, -0.52896565,  1.51822248,  1.59655718, -1.32920591],
       [ 0.50012926, -0.75360832, -0.03861629, -0.52472082,  1.09061382]])

array([[-1.88145979, -0.33694765,  1.00329733, -0.78862807, -0.95450456],
       [ 1.3872682 , -1.05838181,  1.38137969, -0.58068211, -1.45203318],
       [-0.1202232 , -0.02930381,  0.46451676, -0.62666937, -0.14675805],
       [-0.30564453,  1.83376643,  0.82751037, -0.63556272,  1.44643513],
       [ 0.63463514, -0.67219484, -0.17806175,  0.81716206, -1.14449609]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [23]:
np.random.randint(20,50,(3,4))

array([[39, 35, 47, 46],
       [28, 29, 20, 44],
       [29, 42, 22, 20]])

array([[41, 44, 49, 32],
       [43, 20, 20, 49],
       [26, 39, 39, 44]])

#### 13. Reshape the array below with the shape of 6x8

In [25]:
ranarr = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [27]:
ranarr.reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [17]:
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [29]:
#reshape with -1
ranarr.reshape(4,-1)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [64]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
#Create array below
mat= 
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [38]:
mat[1:3,1:3]
# ya da yok...

array([ 6, 11, 16])

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [39]:
mat[:,0]

array([ 1,  5,  9, 13])

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [40]:
mat[1,::2]

array([5, 7])

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [41]:
mat[:,2] = 77

In [42]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [30]:

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [45]:
mat[[1,3],[0,1]] # (1,0) ve (3,1)

array([ 5, 14])

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [46]:
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [48]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [50]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [54]:
mat1 = mat[mat<10] + mat[mat>12]
mat1

array([78, 79, 81, 18, 20, 85, 25])

In [33]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

array([1, 2, 4, 5, 6, 8, 9])

array([77, 77, 77, 13, 14, 77, 16])

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [55]:
mat1.std()

29.700546274093877

29.700546274093877

#### 22. Get the sum of the second column from array above

In [62]:
mat[:,1].sum()
# ya da 
np.sum(mat[:,1])
# ya da
mat.sum(axis=0)[1]

32

In [38]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

32

#### 23. Get the median, mean and std of 3rd row from array above

In [67]:
np.mean(mat[2])

10.5

In [69]:
np.median(mat[2])

10.5

In [70]:
np.std(mat[2])

1.118033988749895

In [45]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
mat[2]

array([ 9, 10, 11, 12])

In [47]:
#median


10.5

In [42]:
#mean


10.5

In [43]:
#std


1.118033988749895

# Pandas Section

In [4]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [72]:
sal=pd.read_csv('Salaries.csv')

In [73]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [74]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [75]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year values are there?**

In [80]:
sal["Year"].value_counts()
# sal["Year"].nunique()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [82]:
sal["TotalPay"].max()

567595.43

In [83]:
sal["TotalPay"].mean()

74768.321971703

In [56]:
#max


567595.43

In [57]:
#avg


74768.321971703

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [88]:
sal["TotalPay"][sal["TotalPay"]>sal["TotalPay"].mean()].count()

69489

In [91]:
# ya da
sal["TotalPay"][sal["TotalPay"]>sal["TotalPay"].mean()].shape[0]

69489

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [102]:
sal["TotalPayBenefits"][sal["EmployeeName"] == "ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [100]:
#ya da 
sal[sal["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is the lowest paid person?**

In [106]:
sal[sal["TotalPay"] == sal["TotalPay"].min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [108]:
# ya da 
sal["EmployeeName"][sal["TotalPay"] == sal["TotalPay"].min()]

148653    Joe Lopez
Name: EmployeeName, dtype: object

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [110]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

In [115]:
sal["JobTitle"].value_counts()

Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ... 
CHIEF HOUSING INSPECTOR                              1
TRAFFIC SIGNAL OPERATOR                              1
COURT COMPUTER FACILITIES COORDINATOR                1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
VICTIM & WITNESS TECHNICIAN                          1
Name: JobTitle, Length: 2159, dtype: int64

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

In [116]:
sal["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

In [117]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [140]:
sal[(sal[sal["Year"] == 2012]) &  (sal[sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()])]

TypeError: unsupported operand type(s) for &: 'float' and 'float'

In [151]:
sal[(sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()) & (sal["Year"] == 2012)].shape[0]
# sal[(sal[sal["Year"] == 2012]) &  (sal[sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()])]

20366

20366

**How many people have a title of Manager in their jobs?**

In [170]:
def fonk(x):
    ret = False
    if "MANAGER" in x.upper():
        ret = True
    return ret

In [171]:
sal[sal["JobTitle"].apply(fonk)]

Id          EmployeeName  \
0            1        NATHANIEL FORD   
83          84        EDWARD REISKIN   
87          88           KEVIN BARRY   
95          96          MIVIC HIROSE   
162        163         JULIE LABONTE   
...        ...                   ...   
147216  147217  Steven D Koneffklatt   
147502  147503    Alice B Villagomez   
147805  147806    Stephen C Laplante   
148150  148151      Shirley M Parker   
148475  148476         James P Horan   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
83      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  230827.12   
87                                         MANAGER VII   96814.36   
95                                        MANAGER VIII  215180.76   
162                                       MANAGER VIII  207501.20   
...                                                ...        ...   
147216                                     Manager III       0.00   
147502                                      Manager IV    1660.00   
147805                                      Manager II       0.00   
148150                           Real Property Manager       0.00   
148475                                      Manager IV     175.75   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0               0.0  400184.25       NaN  567595.43         567595.43  2011   
83              0.0       0.00       NaN  230827.12         230827.12  2011   
87              0.0  133563.47       NaN  230377.83         230377.83  2011   
95              0.0   12000.00       NaN  227180.76         227180.76  2011   
162             0.0    2903.37       NaN  210404.57         210404.57  2011   
...             ...        ...       ...        ...               ...   ...   
147216          0.0    1890.72    342.03    1890.72           2232.75  2014   
147502          0.0       0.00     16.60    1660.00           1676.60  2014   
147805          0.0     982.62    177.76     982.62           1160.38  2014   
148150          0.0     647.76      0.00     647.76            647.76  2014   
148475          0.0       0.00      1.41     175.75            177.16  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
83        NaN  San Francisco     NaN  
87        NaN  San Francisco     NaN  
95        NaN  San Francisco     NaN  
162       NaN  San Francisco     NaN  
...       ...            ...     ...  
147216    NaN  San Francisco     NaN  
147502    NaN  San Francisco     NaN  
147805    NaN  San Francisco     NaN  
148150    NaN  San Francisco     NaN  
148475    NaN  San Francisco     NaN  

[4110 rows x 13 columns]

In [167]:
# sal[sal["JobTitle"].apply(fonk)]
sal[sal["JobTitle"].apply(lambda x: "MANAGER" in x.upper())].shape[0]

4110

In [71]:
#use apply function here


4110

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [173]:
sal_new = sal.iloc[:,[0,1,2,7,8]]

In [174]:
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

In [73]:
sal_new=
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [178]:
sal_new1 = sal.loc[:,"EmployeeName":"TotalPayBenefits"]
sal_new1

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

In [75]:
sal_new=
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [184]:
sal["EmployeeName"][(sal["TotalPayBenefits"] > sal["TotalPayBenefits"].min()) & 
                    
                    (sal["TotalPayBenefits"] < sal["TotalPayBenefits"].mean())]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___